### ISSUE TITLE
Add Stdout logging

### ISSUE THREAD

**Issue by shirhatti** [microsoft/IIS.ServiceMonitor#1]
Based on feedback from @artisticcheese in https://github.com/Microsoft/iis-docker/issues/44, we should consider writing w3c logs to stdout.

**Comment by artisticcheese** [comment]
I would suggest instead use ETW events and consume them instead of tailing physical file log for multiple reasons.

**Comment by shirhatti** [comment]
Agreed. I'm leaning to use ETW as well and we will verify this hypothesis before implementation.

**Comment by shirhatti** [comment]
Re-opening this issue per feedback in https://github.com/Microsoft/IIS.ServiceMonitor/pull/20#issuecomment-399576040

**Comment by bariscaglar** [comment]
The plan is to have a reusable module that listens on the IIS ETW events and writes to an output stream. The design will be similar to that of w3logsvc.

**Comment by tekmaven** [comment]
The previous attempt printed IIS log file data.  I do agree this should be written to stdout, but I think there is a greater need here for overall control of stdout of the container from an IIS site.  We are using NLog extensively in a .NET Framework ASP.NET application and would like to add our own application log data to the output of the container as well.

**Comment by bearkat2173** [comment]
ASP.Net logs app crashes to the _Application_ event log.  Don't we need some type of facility to port ETW messages from container to host?

**Comment by gerich-home** [comment]
Any plans on implementing this feature?

**Comment by benc-uk** [comment]
Any update? Running IIS via this image in Kubernetes and not being able to to do `kubectl logs` is a huge headache. How do people use this image without logs?

**Comment by Rod-Sychev** [comment]
I can't believe this issue still hasn't been resolved!

**Comment by anarsen** [comment]
> Any update? Running IIS via this image in Kubernetes and not being able to to do `kubectl logs` is a huge headache. How do people use this image without logs?

You *could* have a sidecar which tails the IIS access logs to stdout. It's far from ideal - I know.

**Comment by geoffreygeslin** [comment]
Seems like this new "LogMonitor" tool can be configured to listen these IIS logs or events :
https://github.com/microsoft/windows-container-tools/tree/master/LogMonitor

I do not have myself a Dockerized Windows IIS based application, but if anyone try it, it would be gread to share the LogMonitor instruction configured in his DockerFile to monitor IIS.

**Comment by jhkimnew** [comment]
I have tested LogMonitor and confirmed it works.  
Here is how I tested the LogMonitor.

1. Download the LogMonitor.exe from https://github.com/microsoft/windows-container-tools/releases and save the file onto a local directory such as C:\LogMonitor.
2. Create DockerFile and LogMonitorConfig.json on the same directory where the LogMonitor.exe is placed

The file content of DockerFile:
```
FROM mcr.microsoft.com/windows/servercore/iis:latest
COPY LogMonitor.exe LogMonitorConfig.json C:/LogMonitor/
COPY ServiceMonitor.exe C:/
ENTRYPOINT C:\LogMonitor\LogMonitor.exe C:\ServiceMonitor.exe w3svc
```

The file content of LogMonitorConfig.json:
```
{
  "LogConfig": {
    "sources": [
      {
        "type": "File",
        "directory": "c:\\inetpub\\logs",
        "filter": "*.log",
        "includeSubdirectories": true
      }
    ]
  }
}
```

3. Build a new image with the DockerFile.

Ex.) Below command the create a new image named "iis-logmonitor"
docker build -t iis-logmonitor .

4. Create a docker container with the newly created image

Ex.) Below command create a new docker container mapping port 5000 to 80
docker run -p 5000:80 iis-logmonitor

5. Send multiple requests with http://localhost:5000
6. Wait for serveral minutes and you will see the IIS log file content is shown as the below screenshot:

```
C:\LogMonitor> docker run -p 5000:80 iis-logmonitor
#Software: Microsoft Internet Information Services 10.0
#Version: 1.0
#Date: 2020-01-08 19:44:44
#Fields: date time s-ip cs-method cs-uri-stem cs-uri-query s-port cs-username c-ip cs(User-Agent) cs(Referer) sc-status sc-substatus sc-win32-status time-taken
2020-01-08 19:44:44 5.5.5.5 GET / - 80 - 5.5.5.5 Mozilla/5.0+(Windows+NT+10.0;+Win64;+x64) - 304 0 64 302
...
```

**Comment by oliver-dungey** [comment]
@jhkimnew Love it, this is exactly what we've been looking for. I can now see ETW events in my containers console. Looking at https://github.com/microsoft/windows-container-tools/blob/master/LogMonitor/src/LogMonitor/sample-config-files/IIS/LogMonitorConfig.json I can see how to configure more file/ETW log sources but there isn't much in the way of documentation - could do with some more examples.

The big question though is can I configure the STDOUT of my web application to appear in the console? I really don't want the container to waste time writing to log files and then thunking them to STDOUT with LogMonitor - I just want the STDOUT stream of the web app redirected to the container output.  Any input much appreciated.
