### ISSUE TITLE
ServiceMonitor.exe should be a downloaded asset.

### ISSUE THREAD

**Issue by shirhatti** [Microsoft/IIS.ServiceMonitor#17]
_From @MichaelSimons on December 7, 2017 22:17_

The ServiceMonitor.exe should be downloaded within the Dockerfile instead of copied from the build context.  The following are reasons to do this.

1. It is currently copied within 6 different locations within the repo.  This number will soon grow with #67.
2. Pulling the resource from a public URL will allow anyone to easily duplicate the ASP.NET Dockerfiles as needed.  There are several scenarios which users may not be able to use the ASP.NET images (e.g. they need to base their Dockerfile on a different base image yet they need ASP.NET support).

One possible place to host this content would be https://dotnetbinaries.blob.core.windows.net/dockerassets.  This is used to host other content needed by the various .NET Dockerfiles.

_Copied from original issue: Microsoft/aspnet-docker#78_

**Comment by mcy94w** [comment]
Resolved https://github.com/Microsoft/iis-docker/issues/79

**Comment by robertoandrade** [comment]
Since you guys are not using GitHub releases or tagging the source to match how does one know what the latest version of this repo is?

https://dotnetbinaries.blob.core.windows.net/servicemonitor/ doesn't seem to list all versions either.

**Comment by shirhatti** [comment]
@robertoandrade I apologize for that. Looks like we weren't pushing tags on GitHub. I've updated the releases on this repo
