### ISSUE TITLE
Typo: "query" is misspelled

### ISSUE THREAD

**Issue by shirhatti** [Microsoft/IIS.ServiceMonitor#2]
https://github.com/Microsoft/IIS.ServiceMonitor/blob/9ffa751e183989ff94e033b6aa6a09e9ca2293d1/src/ServiceMonitor/ServiceMonitor.cpp#L116

From https://github.com/Microsoft/aspnet-docker/issues/43

**Comment by colmprunty** [comment]
https://github.com/Microsoft/IIS.ServiceMonitor/pull/3
