### ISSUE TITLE
Environment variable names are converted to uppercase in the container

### ISSUE THREAD

**Issue by vjgn** [Microsoft/IIS.ServiceMonitor#32]
ServiceMonitor converts the environment variable names to upper case when adding to the app pool process. 
Below line in IISConfigUtil.cpp seems to do a in place conversion of the environment name to upper case. `FilterEnv(filter, CharUpper(pstrNameCheck), pstrValue)`
This is causing environment variable replacement using ConfigBuilders to fail unless we change all AppSetting keys to be upper case which is not ideal.

**Comment by vjgn** [comment]
Any ETA on the fix. Thank you.

**Comment by shirhatti** [comment]
Fixed in #33

**Comment by gislikonrad** [comment]
Any news on a release, or do I need to compile this myself?

**Comment by shirhatti** [comment]
@bariscaglar looks like this slipped through the cracks. Do you have someone who can take a look at releasing this?

**Comment by shirhatti** [comment]
Actually looks like I misspoke. 2.0.1.6 has this change in it already

**Comment by shirhatti** [comment]
Jumped the gun on that. Looked back on the build history. 2.0.1.6 was built from 5f6d9673131817e52b481f8005cc782c90290860
