### ISSUE TITLE
Environment Variables Value Should Be Convert to LongPathName

### ISSUE THREAD

**Issue by mcy94w** [Microsoft/IIS.ServiceMonitor#35]
There are cases that ServiceMontor.exe will get Environment Variables Value as Short Path Name. They need to be convert to full path name before add to ApplicationHost.config.

**env NAME:|TEMP| VALUE:|C:\Users\CONTAI~1\AppData\Local\Temp| will be added
env NAME:|TMP| VALUE:|C:\Users\CONTAI~1\AppData\Local\Temp| will be added**

**Comment by mcy94w** [comment]
Set NtfsDisable8dot3NameCreation registry key to value ‘2’ can resolve this issue.

**Comment by bariscaglar** [comment]
Workaround should be sufficient. There's no urgency to fix this right now.
