### ISSUE TITLE
Won't start without DefaultAppPool

### ISSUE THREAD

**Issue by FrancisGrignon** [Microsoft/IIS.ServiceMonitor#38]
Hi,

I'm not sure if it's a bug or a feature. 

If we delete the DefaultAppPool, ServiceMonitor return this error:

Service 'w3svc' has been stopped
APPCMD failed with error code 4312
Failed to update IIS configuration

I do delete the DefaultAppPool because I don't use it in my Docker image. Maybe it's a bad practice to do that.

I did notice in the code that then environment variables are updated in the DefaultAppPool `configHelper.UpdateEnvironmentVarsToConfig(L"DefaultAppPool")`. Which explain why ServiceMonitor is not happy about the missing DefaultAppPool.

Thanks in advance.

Francis

**Comment by michha** [comment]
This is related to my pull request #31

**Comment by shirhatti** [comment]
Fixed in #31
