### ISSUE TITLE
APPCMD Error 13 when environment variable value contains a single quote

### ISSUE THREAD

**Issue by rongriffin** [microsoft/IIS.ServiceMonitor#40]
If an environment variable contains a single quote, I get the following error:

`Service 'w3svc' has been stopped
APPCMD failed with error code 13
Failed to update IIS configuration`

Since appcmd.exe is just being used to write environment variables to applicationHost.config, should it XML encode the data?

**Comment by rongriffin** [comment]
I tried to encode the single quote as `&apos;` in the environment variables before I ran `ServiceMonitor.exe`.  

`AppCmd.exe` must already handle XML encoding, because it landed in `applicationHost.config` double encoded as `&amp;apos;`.  

So, a single quote breaks `AppCmd`, but pre-encoding results in double encoding and breaks my application.  Any suggestions for a workaround?

**Comment by rongriffin** [comment]
We get error 87 if there is a double quote in the environment variable also because the appcmd arguments get terminated prematurely.

@jdebbink is going to update his pull request. #41

**Comment by jhkimnew** [comment]
This is fixed on https://github.com/microsoft/IIS.ServiceMonitor/releases/tag/v2.0.1.10.
