### ISSUE TITLE
Create new release (2.0.1.7)

### ISSUE THREAD

**Issue by shirhatti** [microsoft/IIS.ServiceMonitor#48]
The latest release of ServiceMonitor.exe was built from 5f6d9673131817e52b481f8005cc782c90290860

**Comment by shirhatti** [comment]
Reported in https://github.com/Microsoft/IIS.ServiceMonitor/issues/32#issuecomment-474899644

**Comment by penenkel** [comment]
Any news on this? As far as I can tell the most recent version version awailable via https://dotnetbinaries.blob.core.windows.net/servicemonitor/2.0.1.x/ServiceMonitor.exe is 2.0.1.6.

Also https://dotnetbinaries.blob.core.windows.net/servicemonitor should list all available versions!

**Comment by gislikonrad** [comment]
I gave up on waiting and ported the service monitor to .net and fixed the bug.

https://solidsoft.works/2019/03/25/porting-iis-servicemonitor-to-net/

https://github.com/SOLIDSoftworks/iis-service-monitor

**Comment by vitaliitylyk** [comment]
Guys, is this going to be released any time soon? Fix for #32 is extremely important for many people and is actually preventing us to use ServiceMonitor because it screws up environment variables

**Comment by Thoorium** [comment]
Hi,
Encountered the uppercase problem today. I was sad to see that the issue had been fixed but never released. For now I'm compiling the exe myself and replacing it when I build my application's image.

**Comment by NaibafCH** [comment]
I just tried the [released binary](https://dotnetbinaries.blob.core.windows.net/servicemonitor/2.0.1.8/ServiceMonitor.exe) and issue #32 is still present. If I build 0d451de0c3dbe7c639e36e8c824f0a50e6cc9fbb myself and use that binary, the problem is gone. Does anyone else have the same experience?

**Comment by vitaliitylyk** [comment]
@sujitnayak as far as I can see, you have released the v2.1.0.8 version. Can you please confirm that this binary is built from [0d451de](https://github.com/microsoft/IIS.ServiceMonitor/commit/0d451de0c3dbe7c639e36e8c824f0a50e6cc9fbb)? https://dotnetbinaries.blob.core.windows.net/servicemonitor/2.0.1.8/ServiceMonitor.exe

**Comment by jhkimnew** [comment]
https://github.com/microsoft/IIS.ServiceMonitor/releases/tag/v2.0.1.8

NOTE: 
The new version (v2.0.1.8) is not linked to the iis container images. That will be done when we regenerate the iis container images.

**Comment by jhkimnew** [comment]
@vitaliitylyk Thanks for reporting the problem. We are working on the issue now.

**Comment by sujitnayak** [comment]
Here's the new release that should fix these issues:

https://github.com/microsoft/IIS.ServiceMonitor/releases/tag/v2.0.1.9

**Comment by vitaliitylyk** [comment]
This works, thank you!
