### ISSUE TITLE
Intermittent errors with HRESULT 800705b4

### ISSUE THREAD

**Issue by MikeChristensen** [Microsoft/IIS.ServiceMonitor#49]
We're running into errors with our Docker images that are using ServiceMonitor.exe as an ENTRYPOINT.  The last thing in the Docker logs is:

`ERROR: Failed to stop or query status of service 'w3svc' error [800705b4]`

Any ideas what would cause this?  Is there a suggested work around?

**Comment by MikeChristensen** [comment]
Perhaps helpful: This seems to occur when you modify the contents of web.config right before you call ServiceMonitor.exe.  It might be some race condition since it doesn't always happen.

**Comment by MikeChristensen** [comment]
If I tail the logs in Docker, here's what I see:

![image](https://user-images.githubusercontent.com/6528426/55507908-9cfe8400-560d-11e9-9220-cad914f65473.png)

So basically we transform some web.config, which causes the app pool to recycle.  We then start ServiceMonitor.exe, which can't query the status of w3svc and immediately exits, causing the container the exit.  This creates an endless loop in Service Fabric, since it then tries to restart the container again.

Expected: ServiceMonitor.exe should handle recycling app pools correctly.

**Comment by MikeChristensen** [comment]
Another annoying thing is when ServiceMonitor.exe exits with this error, it still returns an EXIT code of 0 so we can't trap the error and retry with a script.

Expected: $LASTEXITCODE should non-zero when the program exits with an error.

**Comment by bariscaglar** [comment]
@MikeChristensen We'll look into this. Thanks for reporting. You can expect a response soon.

**Comment by jhkimnew** [comment]
@MikeChristensen Would you make a simplified dockerfile, which is reproducing the issue and then share it so that I can reproduce the issue and then fix the issue?

I'd like to inform that the error 800705b4 you reported means that there was a timeout error. 
ServiceMonitor uses 20 seconds timeout for retrying (3~4 times) to get the service status after restarting w3svc. If it fails to get the service running state in 20 seconds, it returns the timeout error. 

There must be some reasons why it took longer time (more than 20 seconds) to make w3svc service being restarted, which causes the failure of ServiceMonitor.

Thanks,
Jeong Hwan Kim
Microsoft

**Comment by jhkimnew** [comment]
@MikeChristensen BTW, I assumed that you ran into the issue when starting container. Thinking again, I might be wrong about that. Would you describe more detail? If you can give the repro steps, that will be very helpful for me to understand how the error can happen.

**Comment by pan-wang** [comment]
ServiceMonitor stops w3svc service first to update applicationhost config with the environmental variables first and then restart the service. When container starts, it also starts the all services. There could be a timing issue that entry program (stopping service) was executed before Service started. To work around it, could you please try adding "net stop w3svc" in your docker file.

**Comment by pan-wang** [comment]
you may also need to reset w3svc start type to manual in docker file, i.e., sc config w3svc start=demand

**Comment by MikeChristensen** [comment]
I've confirmed this workaround solves the issue.  Basically, set the startup behavior to demand in the dockerfile, and set the entrypoint to transform the config files then run ServiceMonitor.exe (which will also start the service).

**Comment by danassetms** [comment]
what does this actually mean?

> Basically, set the startup behavior to demand in the dockerfile, and set the entrypoint to transform the config files then run ServiceMonitor.exe

What do we have to do to fix the issue?

**Comment by jhkimnew** [comment]
The first set means to add "RUN sc config w3svc start=demand" as the below example dockerfile and the second one to replace the last line ("ENTRYPOINT ["C:\\ServiceMonitor.exe", "w3svc"]) with calling your own  batch file which does the configuration job and put "c:\servicemonitor w3svc" at the end of the batch file.

```
FROM mcr.microsoft.com/windows/servercore/iis:latest

RUN powershell -Command Add-WindowsFeature Web-Server
RUN sc config w3svc start=demand
EXPOSE 80
ENTRYPOINT ["C:\\ServiceMonitor.exe", "w3svc"]
```

**Comment by danassetms** [comment]
That's perfect! Thanks for the example

**Comment by danassetms** [comment]
I'm getting the following error with this example: 
A positional parameter cannot be found that accepts argument 

Any ideas?

**Comment by danassetms** [comment]
Fixed the postional parameter issue with the following:
RUN powershell -Command Set-Service -Name aspnet_state -StartupType 'Manual'

**Comment by danassetms** [comment]
However I still have the ServiceMonitor issue - it keeps preventing a container starting and then just randomly recycles several times.  I have other containers with the same setup that work fine for a bit and then will crash with the same error later down the line.

Someone suggested updating Service Monitor but again gave no instructions

**Comment by pan-wang** [comment]
Do you have the docker log for the error case?

**Comment by danassetms** [comment]
Task Log: ERROR: Failed to stop or query status of service 'w3svc' error [800705b4]

**Comment by jhkimnew** [comment]
I think you used the wrong service name (aspnet_state).  The right service name is w3svc as the following:
```
RUN powershell -Command Set-Service -Name w3svc -StartupType 'Manual'
```

**Comment by pan-wang** [comment]
800705b4 means timeout. It seams ServiceMonitor had trouble to access W3SVC service. Did you set W3SVC service to manual start mode in docker file? you said you had the same setup work fine for a bit and then will crash later,  could you please give more details? Could you please check whether your container image is compatible with the host OS?

**Comment by danassetms** [comment]
Correct the start service to w3svc and startup type to manual and the service now just recycles over and over with nothing in the logs.  It looks like the  w3svc isn't starting and keeping the container open

Docker file:
FROM mcr.microsoft.com/dotnet/framework/aspnet:4.7.2-windowsservercore-ltsc2019 AS base
WORKDIR /inetpub/wwwroot
EXPOSE 80

FROM mcr.microsoft.com/dotnet/framework/sdk:4.7.2-windowsservercore-ltsc2019 AS build
WORKDIR /app

# copy csproj and restore as distinct layers
COPY . .
RUN nuget restore ./Website.csproj -SolutionDirectory ./..

# build app
RUN msbuild ./Website.csproj /p:Configuration=Release /p:DebugSymbols=false /p:DebugType=None /p:DeployOnBuild=true /p:PublishProfile=FolderProfile.pubxml

FROM base as runtime
ARG source
COPY --from=build /app/bin/Release/Publish/. ./

RUN powershell -Command Set-Service -Name w3svc -StartupType 'Manual'

COPY docker-entrypoint.ps1 /
ENTRYPOINT powershell -File C:\docker-entrypoint.ps1

**Comment by pan-wang** [comment]
I assume you tried to build you project and publish it inside container to IIS and then access app. Could you please check whether the build succeeded and content was dropped correctly? Could you please share docker-entrypoint.ps1  so that we can make sure ServiceMonitor is in the picture? If possible, please open another issue as your problem seems not related with ServiceMonitor itself.
