### ISSUE TITLE
Make Start/stop timeout configurable

### ISSUE THREAD

**Issue by fgather** [Microsoft/IIS.ServiceMonitor#5]
Sometimes our IIS container does not start up since the timeout of 20 seconds is quite low for a large site spinned up on a machine with high load. Could you add an additional option to set the timeout as commandline parameter?

**Comment by shirhatti** [comment]
As far as I'm aware, there's no 20 seconds timeout in ServiceMonitor. What error are you seeing?

**Comment by bariscaglar** [comment]
Looks like we did not get the follow up answer here. Please reactivate if you are still having problems.

**Comment by gitfool** [comment]
I'm seeing with some windows services that take too long to start and have recently been containerized. SM waits for 20s:
https://github.com/microsoft/IIS.ServiceMonitor/blob/1c4153056fd8ad8e61317af115153180dc10c2cc/src/ServiceMonitor/Main.cpp#L94
https://github.com/microsoft/IIS.ServiceMonitor/blob/1c4153056fd8ad8e61317af115153180dc10c2cc/src/ServiceMonitor/ServiceMonitor.h#L26
Please make this configurable from the command-line.
