### ISSUE TITLE
Handle environment variable with single

### ISSUE THREAD

**Issue by jvano** [microsoft/IIS.ServiceMonitor#58]
I'm using microsoft/iis on Win2019 RS5 and whenever I pass an environment variable with single quote, the container exits when trying to start.

For example: 
ABC=a'b

If I override the entrypoint with my own custom script, the container starts fine.

**Comment by jhkimnew** [comment]
This is fixed on https://github.com/microsoft/IIS.ServiceMonitor/releases/tag/v2.0.1.10.
